In [1]:
# import sys, os, re; sys.path = (["../src/", "../"] if re.match(r'^(\w\:\\)|(/)', os.getcwd()) else [])+ sys.path 

import qubx
%qubxd

%load_ext autoreload
%autoreload 2

from qubx.connectors.ccxt.utils import ccxt_convert_deal_info


⠀⠀⡰⡖⠒⠒⢒⢦⠀⠀   
⠀⢠⠃⠈⢆⣀⣎⣀⣱⡀  QUBX | Quantitative Backtesting Environment 
⠀⢳⠒⠒⡞⠚⡄⠀⡰⠁         (c) 2025, ver. 0.6.10
⠀⠀⠱⣜⣀⣀⣈⣦⠃⠀⠀⠀ 
        


In [ ]:
{'27283823387': ['1002968908', '1002968909', '1002968910', '1002968911', '1002968912', '1002968913']})

In [2]:
deals = [
    { # - Report 1
        "info": {
            "s": "DOTUSDT", "c": "qubx_DOTUSDT_17424567042", "S": "BUY", "o": "MARKET", "f": "GTC",
            "q": "52.3", "p": "0", "ap": "4.465", "sp": "0",
            "x": "TRADE", "X": "PARTIALLY_FILLED",
            "i": 27283438093, "l": "32.8", "z": "32.8", "L": "4.465", "n": "0.073226", "N": "USDT",
            "T": 1742456841238, "t": 1002957674, 
            "b": "0", "a": "0", "m": False, "R": False, "wt": "CONTRACT_PRICE", "ot": "MARKET", "ps": "BOTH", "cp": False, "rp": "0", "pP": False, "si": 0, "ss": 0, "V": "EXPIRE_MAKER", "pm": "NONE", "gtd": 0,
        },
        "timestamp": 1742456841238, "datetime": "2025-03-20T07:47:21.238Z", "symbol": "DOT/USDT:USDT",
        "id": "1002957674", "order": "27283438093", "type": "market", "takerOrMaker": "taker", "side": "buy", 
        "price": 4.465, "amount": 32.8, "cost": 146.452,
        "fee": {"currency": "USDT", "cost": 0.073226}, "fees": [{"currency": "USDT", "cost": 0.073226}],
    },
    {# - Report 2
        "info": {
            "s": "DOTUSDT", "c": "qubx_DOTUSDT_17424567042", "S": "BUY", "o": "MARKET", "f": "GTC",
            "q": "52.3", "p": "0", "ap": "4.465", "sp": "0",
            "x": "TRADE", "X": "PARTIALLY_FILLED",
            "i": 27283438093, "l": "32.8", "z": "32.8", "L": "4.465", "n": "0.073226", "N": "USDT",
            "T": 1742456841238, "t": 1002957674,
            "b": "0", "a": "0", "m": False, "R": False, "wt": "CONTRACT_PRICE", "ot": "MARKET", "ps": "BOTH", "cp": False, "rp": "0", "pP": False, "si": 0, "ss": 0, "V": "EXPIRE_MAKER", "pm": "NONE", "gtd": 0,
        },
        "timestamp": 1742456841238, "datetime": "2025-03-20T07:47:21.238Z", "symbol": "DOT/USDT:USDT",
        "id": "1002957674", "order": "27283438093", "type": "market", "takerOrMaker": "taker", "side": "buy",
        "price": 4.465, "amount": 32.8, "cost": 146.452,
        "fee": {"currency": "USDT", "cost": 0.073226}, "fees": [{"currency": "USDT", "cost": 0.073226}],
    },
    { # - Report 3
        "info": {
            "s": "DOTUSDT", "c": "qubx_DOTUSDT_17424567042", "S": "BUY", "o": "MARKET", "f": "GTC",
            "q": "52.3", "p": "0", "ap": "4.465", "sp": "0",
            "x": "TRADE", "X": "FILLED", "i": 27283438093,
            "l": "19.5", "z": "52.3", "L": "4.465", "n": "0.04353375", "N": "USDT",
            "T": 1742456841238, "t": 1002957675,
            "b": "0", "a": "0", "m": False, "R": False, "wt": "CONTRACT_PRICE", "ot": "MARKET", "ps": "BOTH", "cp": False, "rp": "0", "pP": False, "si": 0, "ss": 0, "V": "EXPIRE_MAKER", "pm": "NONE", "gtd": 0,
        },
        "timestamp": 1742456841238, "datetime": "2025-03-20T07:47:21.238Z", "symbol": "DOT/USDT:USDT", 
        "id": "1002957675", "order": "27283438093", "type": "market", "takerOrMaker": "taker", "side": "buy", 
        "price": 4.465, "amount": 19.5, "cost": 87.0675,
        "fee": {"currency": "USDT", "cost": 0.04353375}, "fees": [{"currency": "USDT", "cost": 0.04353375}],
    },
]

In [4]:
for d in deals:
    print(ccxt_convert_deal_info(d))

Deal(id='1002957674', order_id='27283438093', time=Timestamp('2025-03-20 07:47:21.238000'), amount=32.8, price=4.465, aggressive=True, fee_amount=0.073226, fee_currency='USDT')
Deal(id='1002957674', order_id='27283438093', time=Timestamp('2025-03-20 07:47:21.238000'), amount=32.8, price=4.465, aggressive=True, fee_amount=0.073226, fee_currency='USDT')
Deal(id='1002957675', order_id='27283438093', time=Timestamp('2025-03-20 07:47:21.238000'), amount=19.5, price=4.465, aggressive=True, fee_amount=0.04353375, fee_currency='USDT')


In [11]:
deals = [
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '2.3', 'z': '2.3', 'L': '4.492', 'n': '0.0051658', 'N': 'USDT', 'T': 1742460383938, 't': 1002968908, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968908', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 2.3, 'cost': 10.3316, 'fee': {'currency': 'USDT', 'cost': 0.0051658}, 'fees': [{'currency': 'USDT', 'cost': 0.0051658}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '2.3', 'z': '2.3', 'L': '4.492', 'n': '0.0051658', 'N': 'USDT', 'T': 1742460383938, 't': 1002968908, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968908', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 2.3, 'cost': 10.3316, 'fee': {'currency': 'USDT', 'cost': 0.0051658}, 'fees': [{'currency': 'USDT', 'cost': 0.0051658}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '1.4', 'z': '3.7', 'L': '4.492', 'n': '0.0031444', 'N': 'USDT', 'T': 1742460383938, 't': 1002968909, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968909', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 1.4, 'cost': 6.2888, 'fee': {'currency': 'USDT', 'cost': 0.0031444}, 'fees': [{'currency': 'USDT', 'cost': 0.0031444}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '2.3', 'z': '2.3', 'L': '4.492', 'n': '0.0051658', 'N': 'USDT', 'T': 1742460383938, 't': 1002968908, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968908', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 2.3, 'cost': 10.3316, 'fee': {'currency': 'USDT', 'cost': 0.0051658}, 'fees': [{'currency': 'USDT', 'cost': 0.0051658}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '1.4', 'z': '3.7', 'L': '4.492', 'n': '0.0031444', 'N': 'USDT', 'T': 1742460383938, 't': 1002968909, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968909', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 1.4, 'cost': 6.2888, 'fee': {'currency': 'USDT', 'cost': 0.0031444}, 'fees': [{'currency': 'USDT', 'cost': 0.0031444}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '4.5', 'z': '8.2', 'L': '4.492', 'n': '0.010107', 'N': 'USDT', 'T': 1742460383938, 't': 1002968910, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968910', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 4.5, 'cost': 20.214, 'fee': {'currency': 'USDT', 'cost': 0.010107}, 'fees': [{'currency': 'USDT', 'cost': 0.010107}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '2.3', 'z': '2.3', 'L': '4.492', 'n': '0.0051658', 'N': 'USDT', 'T': 1742460383938, 't': 1002968908, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968908', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 2.3, 'cost': 10.3316, 'fee': {'currency': 'USDT', 'cost': 0.0051658}, 'fees': [{'currency': 'USDT', 'cost': 0.0051658}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '1.4', 'z': '3.7', 'L': '4.492', 'n': '0.0031444', 'N': 'USDT', 'T': 1742460383938, 't': 1002968909, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968909', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 1.4, 'cost': 6.2888, 'fee': {'currency': 'USDT', 'cost': 0.0031444}, 'fees': [{'currency': 'USDT', 'cost': 0.0031444}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '4.5', 'z': '8.2', 'L': '4.492', 'n': '0.010107', 'N': 'USDT', 'T': 1742460383938, 't': 1002968910, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968910', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 4.5, 'cost': 20.214, 'fee': {'currency': 'USDT', 'cost': 0.010107}, 'fees': [{'currency': 'USDT', 'cost': 0.010107}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '8.5', 'z': '16.7', 'L': '4.492', 'n': '0.019091', 'N': 'USDT', 'T': 1742460383938, 't': 1002968911, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968911', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 8.5, 'cost': 38.182, 'fee': {'currency': 'USDT', 'cost': 0.019091}, 'fees': [{'currency': 'USDT', 'cost': 0.019091}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '2.3', 'z': '2.3', 'L': '4.492', 'n': '0.0051658', 'N': 'USDT', 'T': 1742460383938, 't': 1002968908, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968908', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 2.3, 'cost': 10.3316, 'fee': {'currency': 'USDT', 'cost': 0.0051658}, 'fees': [{'currency': 'USDT', 'cost': 0.0051658}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '1.4', 'z': '3.7', 'L': '4.492', 'n': '0.0031444', 'N': 'USDT', 'T': 1742460383938, 't': 1002968909, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968909', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 1.4, 'cost': 6.2888, 'fee': {'currency': 'USDT', 'cost': 0.0031444}, 'fees': [{'currency': 'USDT', 'cost': 0.0031444}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '4.5', 'z': '8.2', 'L': '4.492', 'n': '0.010107', 'N': 'USDT', 'T': 1742460383938, 't': 1002968910, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968910', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 4.5, 'cost': 20.214, 'fee': {'currency': 'USDT', 'cost': 0.010107}, 'fees': [{'currency': 'USDT', 'cost': 0.010107}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '8.5', 'z': '16.7', 'L': '4.492', 'n': '0.019091', 'N': 'USDT', 'T': 1742460383938, 't': 1002968911, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968911', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 8.5, 'cost': 38.182, 'fee': {'currency': 'USDT', 'cost': 0.019091}, 'fees': [{'currency': 'USDT', 'cost': 0.019091}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '4.8', 'z': '21.5', 'L': '4.492', 'n': '0.0107808', 'N': 'USDT', 'T': 1742460383938, 't': 1002968912, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968912', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 4.8, 'cost': 21.5616, 'fee': {'currency': 'USDT', 'cost': 0.0107808}, 'fees': [{'currency': 'USDT', 'cost': 0.0107808}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '2.3', 'z': '2.3', 'L': '4.492', 'n': '0.0051658', 'N': 'USDT', 'T': 1742460383938, 't': 1002968908, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968908', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 2.3, 'cost': 10.3316, 'fee': {'currency': 'USDT', 'cost': 0.0051658}, 'fees': [{'currency': 'USDT', 'cost': 0.0051658}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '1.4', 'z': '3.7', 'L': '4.492', 'n': '0.0031444', 'N': 'USDT', 'T': 1742460383938, 't': 1002968909, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968909', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 1.4, 'cost': 6.2888, 'fee': {'currency': 'USDT', 'cost': 0.0031444}, 'fees': [{'currency': 'USDT', 'cost': 0.0031444}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '4.5', 'z': '8.2', 'L': '4.492', 'n': '0.010107', 'N': 'USDT', 'T': 1742460383938, 't': 1002968910, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968910', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 4.5, 'cost': 20.214, 'fee': {'currency': 'USDT', 'cost': 0.010107}, 'fees': [{'currency': 'USDT', 'cost': 0.010107}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '8.5', 'z': '16.7', 'L': '4.492', 'n': '0.019091', 'N': 'USDT', 'T': 1742460383938, 't': 1002968911, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968911', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 8.5, 'cost': 38.182, 'fee': {'currency': 'USDT', 'cost': 0.019091}, 'fees': [{'currency': 'USDT', 'cost': 0.019091}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'PARTIALLY_FILLED', 'i': 27283823387, 'l': '4.8', 'z': '21.5', 'L': '4.492', 'n': '0.0107808', 'N': 'USDT', 'T': 1742460383938, 't': 1002968912, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968912', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 4.8, 'cost': 21.5616, 'fee': {'currency': 'USDT', 'cost': 0.0107808}, 'fees': [{'currency': 'USDT', 'cost': 0.0107808}]},
	{'info': {'s': 'DOTUSDT', 'c': 'qubx_DOTUSDT_17424603827', 'S': 'BUY', 'o': 'MARKET', 'f': 'GTC', 'q': '23.6', 'p': '0', 'ap': '4.492', 'sp': '0', 'x': 'TRADE', 'X': 'FILLED', 'i': 27283823387, 'l': '2.1', 'z': '23.6', 'L': '4.492', 'n': '0.00471659', 'N': 'USDT', 'T': 1742460383938, 't': 1002968913, 'b': '0', 'a': '0', 'm': False, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'MARKET', 'ps': 'BOTH', 'cp': False, 'rp': '0', 'pP': False, 'si': 0, 'ss': 0, 'V': 'EXPIRE_MAKER', 'pm': 'NONE', 'gtd': 0}, 'timestamp': 1742460383938, 'datetime': '2025-03-20T08:46:23.938Z', 'symbol': 'DOT/USDT:USDT', 'id': '1002968913', 'order': '27283823387', 'type': 'market', 'takerOrMaker': 'taker', 'side': 'buy', 'price': 4.492, 'amount': 2.1, 'cost': 9.4332, 'fee': {'currency': 'USDT', 'cost': 0.00471659}, 'fees': [{'currency': 'USDT', 'cost': 0.00471659}]},
 ]

In [ ]:
{'27283823387': ['1002968908', '1002968909', '1002968910', '1002968911', '1002968912', '1002968913']}

In [15]:
s = 0
for d in deals:
    print(di:=ccxt_convert_deal_info(d))
    s+=di.amount

Deal(id='1002968908', order_id='27283823387', time=Timestamp('2025-03-20 08:46:23.938000'), amount=2.3, price=4.492, aggressive=True, fee_amount=0.0051658, fee_currency='USDT')
Deal(id='1002968908', order_id='27283823387', time=Timestamp('2025-03-20 08:46:23.938000'), amount=2.3, price=4.492, aggressive=True, fee_amount=0.0051658, fee_currency='USDT')
Deal(id='1002968909', order_id='27283823387', time=Timestamp('2025-03-20 08:46:23.938000'), amount=1.4, price=4.492, aggressive=True, fee_amount=0.0031444, fee_currency='USDT')
Deal(id='1002968908', order_id='27283823387', time=Timestamp('2025-03-20 08:46:23.938000'), amount=2.3, price=4.492, aggressive=True, fee_amount=0.0051658, fee_currency='USDT')
Deal(id='1002968909', order_id='27283823387', time=Timestamp('2025-03-20 08:46:23.938000'), amount=1.4, price=4.492, aggressive=True, fee_amount=0.0031444, fee_currency='USDT')
Deal(id='1002968910', order_id='27283823387', time=Timestamp('2025-03-20 08:46:23.938000'), amount=4.5, price=4.492

In [ ]:
s

37.99999999999999

<pre>
2025-03-20 08:46:24.067 [🐞]   [SimplePositionGatherer(BINANCE.UM:SWAP:DOTUSDT)] :: Position is adjusted from 0.0 to 23.6 : [27283823387] MARKET BUY 23.6 of BINANCE.UM:SWAP:DOTUSDT @ 4.492 (GTC) [CLOSED]
2025-03-20 08:46:24.119 [🐞]   [CcxtAccountProcessor(BINANCE.UM:SWAP:DOTUSDT)] :: New status for order 27283823387 -> OPEN (MARKET BUY 23.6)
2025-03-20 08:46:24.127 [🐞]   [CcxtAccountProcessor(BINANCE.UM:SWAP:DOTUSDT)] :: New status for order 27283823387 -> OPEN (MARKET BUY 23.6 @ 4.492)
2025-03-20 08:46:24.136 [🐞]   [CcxtAccountProcessor(BINANCE.UM:SWAP:DOTUSDT)] :: traded 2.3 @ 4.492 -> 0.00 USDT realized profit
2025-03-20 08:46:24.218 [🐞]   [CcxtAccountProcessor(BINANCE.UM:SWAP:DOTUSDT)] :: traded 1.4 @ 4.492 -> 0.00 USDT realized profit
2025-03-20 08:46:24.247 [🐞]   [CcxtAccountProcessor(BINANCE.UM:SWAP:DOTUSDT)] :: traded 4.5 @ 4.492 -> 0.00 USDT realized profit
2025-03-20 08:46:24.272 [🐞]   [CcxtAccountProcessor(BINANCE.UM:SWAP:DOTUSDT)] :: traded 8.5 @ 4.492 -> 0.00 USDT realized profit
2025-03-20 08:46:24.290 [🐞]   [CcxtAccountProcessor(BINANCE.UM:SWAP:DOTUSDT)] :: traded 4.8 @ 4.492 -> 0.00 USDT realized profit
2025-03-20 08:46:24.316 [🐞]   [CcxtAccountProcessor(BINANCE.UM:SWAP:DOTUSDT)] :: traded 2.1 @ 4.492 -> 0.00 USDT realized profit

In [18]:
2.3 + 1.4 + 4.5 + 8.5 + 4.8 + 2.1

23.6