name: Qubx CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run style checks with ruff
        run: |
          pip install ruff
          ruff check . --output-format=github --exclude=experiments --exit-zero

  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install dependencies and compile Cython
        run: just install

      - name: Run unit tests
        run: just test
