name: Run Pytest on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Just and Poetry
      run: |
        curl -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin/
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - name: Install dependencies
      run: |
        just dev-install

    - name: Run tests
      run: |
        just test